version: "3"

services:
    app:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./dev_framework:/dev_framework
        command: >
            sh -c "node compile.js Inbox.sol; npm run test"